export const illustrator="https://www.adobe.com/ca/products/illustrator.html"
export const grommet="https://v2.grommet.io/"
export const createReactApp="https://reactjs.org/docs/create-a-new-react-app.html"
export const styledComponents="https://styled-components.com/"
export const githubWeb="https://github.com/reagantakeuchi/reagantakeuchi-web"
export const githubProf="https://github.com/reagantakeuchi"
export const linkedin = "https://www.linkedin.com/in/reagan-takeuchi-a647421b9/"
export const instagram = "https://www.instagram.com/designbyrea/"